services:
  postgres-master:
    image: bitnami/postgresql:14
    container_name: postgres-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=code_rating
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replica123
    volumes:
      - ./postgres-master/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/postgres_master:/bitnami/postgresql
    ports:
      - "5433:5432"

  postgres-replica:
    image: bitnami/postgresql:14
    container_name: postgres-replica
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replica123
    depends_on:
      - postgres-master
    volumes:
      - ./data/postgres_replica:/bitnami/postgresql
    ports:
      - "5434:5432"

  frontend:
    build:
      context: ../frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
