events {}

http {
    upstream backend {
        server 192.168.56.11:3000; 
        server 192.168.56.12:3001;
    }

    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
